CREATE TABLE SALES
(
   DEPT_NO   NUMBER,
   PART_NO   VARCHAR2(10 Byte),
   COUNTRY   VARCHAR2(20 Byte),
   AMOUNT    NUMBER,
   ORDER_NO  NUMBER(20)
)
ENABLE ROW MOVEMENT
PARTITION BY LIST (COUNTRY)
(
  PARTITION EU VALUES ('FRANCE', 'ITALY') NOCOMPRESS,
  PARTITION AF VALUES ('SOUTH AFRICA') NOCOMPRESS,
  PARTITION AA VALUES ('INDIA', 'CHINA', 'PAKISTAN') NOCOMPRESS,
  PARTITION NA VALUES ('US', 'CANADA') NOCOMPRESS
)
TABLESPACE USERS;

CREATE UNIQUE INDEX ORDER_NO
   ON SALES (ORDER_NO ASC)
   TABLESPACE USERS;
