:source-highlighter: pygments

= Notes for SEPA Compliance 2019
This is all about SEPA Integration Test
:sectnums:
:toc:
:toclevels: 4
:toc-title: Table of Contents

:description: Example AsciiDoc document
:keywords: AsciiDoc
:imagesdir: ./img

SEPA `compliance tests` include #both# outbound and inbound tests.

.Formated Text

bold *constrained* & **un**constrained

italic _constrained_ & __un__constrained

bold italic *_constrained_* & **__un__**constrained

monospace `constrained` & ``un``constrained

monospace bold `*constrained*` & ``**un**``constrained

monospace italic `_constrained_` & ``__un__``constrained

monospace bold italic `*_constrained_*` & ``**__un__**``constrained

== Inbound
Yang Wang <wy8162@gmail.com>

The purpose of this work order is to backport the changes we made for SEPA Compliance 2019 for EBA Step2.

* *camt.027*: claim inquiry
** Inbound from IP
** Inbound from ESC

. *camt.029*: response to claim inquiry
.. Inbound from IP
.. Inbound from ESC


[cols="2,2,2,4a"]
|===
|Header 1 |Header 2 |Header 3 |Header 4

|Column 1, row 1
|Column 2, row 1
|Column 3, row 1
|Column 4, row 1

* List item1
* List item2

|ISO20022
|SEPA Compliance
|SWIFT
|ACH Format
|===


=== Inbound Claim Inquiry Response camt.029

=== Inbound Claim Inquiry camt.027

== Outbound

The purpose of this work order is to backport the changes we made for SEPA Compliance 2019.

== Implementation
[source,java, numbered]
        public ClaimResponseMatched(String caseId, String claimResponseStatusCode)
        {
            super(LOG_EVENT_CLAIM_RESPONSE_MATCHED_WITH_STATUS_CODE);
            setParameter(1, caseId, Q5Constant.STRING);
            setParameter(2, claimResponseStatusCode, Q5Constant.STRING);
        }

[TIP]
====
Think of c1..c2 as _all commits as of c1 (not including c1) until commit
c2.
====

TIP: another TIP

[WARNING]
====
This is a warning
====

WARNING: another warning

.My header for the note
[NOTE]
====
Blabla
====

NOTE: another note

IMPORTANT: this is important stuffs

.Unordered List
* 1
** 1.1
* 2
** 2.2

.Ordered List
. 1
.. 1.1

//- serves as end of list

. 2
.. 2.1

//-

CPU:: The brain of the computer.
Hard drive:: Permanent storage for operating system and/or user files.
RAM:: Temporarily stores information the CPU uses during operation.
Keyboard:: Used to enter text or control items on the screen.
Mouse:: Used to point to and select items on your computer screen.
Monitor:: Displays information in visual form using text and graphics.

Operating Systems::
Linux:::
. Fedora
* Desktop
. Ubuntu
* Desktop
* Server
BSD:::
. FreeBSD
. NetBSD

Cloud Providers::
PaaS:::
. OpenShift
. CloudBees
IaaS:::
. Amazon EC2
. Rackspace

== Reference

https://www.vogella.com/tutorials/AsciiDoc/article.html[Using AsciiDoc and Asciidoctor to write documentation - Tutorial]

